### ISSUE TITLE
sass编译报错

### ISSUE THREAD

**Issue by easyigh** [stbui/angular2-material2-bootstrap4-admin-app#2]
File to import not found or unreadable: ~@angular/material/core/theming/all-theme
你原来用的是什么版本的material，现在material已没有material/core目录

**Comment by easyigh** [comment]
自问自答了，要手动指定版本安装material:
npm install --save @angular/material@2.0.0-beta.2

**Comment by stbui** [comment]
是的，angular版本发布4以后 material 同时也发了新的版本，package默认指定安装最新版本的material，所以导致编译不通过

在 2017-06-12 10:53:22，"easyigh" <notifications@github.com> 写道：


自问自答了，要手动指定版本安装material:
npm install --save @2.0.0-beta.2
